#!/bin/bash

# Copyright: 2023 Virtuozzo International GmbH

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

inherit default os envinfo;
VERSION="1";
DEFAULT_ACTION="Usage";
DESCRIPTION="Manage Apache2 modules";

APACHE2_CONF='/etc/httpd/conf.d/modules.conf';

function doUsage() {
    showUsageMessage;
}

function doEnmod(){
	local module=$1;
	sed -i "/^#LoadModule.*$module.*/ s/^#LoadModule/LoadModule/" $APACHE2_CONF;
	restartServiceSilent ${SERVICE};
}

function doDismod(){
	local module=$1;
	sed -i "/^LoadModule.*$module.*/ s/LoadModule/#LoadModule/" $APACHE2_CONF;
	restartServiceSilent ${SERVICE};
}
function describeEnmod(){
	echo "<module> enable apache2 module";
}

function describeDismod(){
	echo "<module> disable apache2 module";
}
