#!/bin/bash

# Copyright: 2023 Virtuozzo International GmbH

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



include net log;


DESCRIPTION="Send API requests to Jelastic";
VERSION="1";
DEFAULT_ACTION="Usage";
VERBOSE=1;
$PROGRAM 'curl';

function doUsage() {
    showUsageMessage;
}

describeApiCall(){
    echo -n "[API_DOMAIN]/path <curl parameters>"
}

doApiCall(){
    local i
    getInfraAddresses infraAddr;
    [[ -z "${domain}" ]] && {
        log  "Cannot obtain core address";
        writeJSONResponseErr "result=>9999" "message=>Cannot get app domain";
        return 1;
    }

    API_PARAMS=();
    for i in "$@"; do
        i="$(sed  -re 's/["]/\\"/g' <<<"$i")"
        API_PARAMS=( "${API_PARAMS[@]}" "\"${i}\"")
    done

    local APP_DOMAIN="https://app.${domain}"
    eval $CURL $(sed -r "s@\[API_DOMAIN\]@$APP_DOMAIN@" <<<"${API_PARAMS[@]}")

}


